[package]
name = "rust-zeppelin"
version = "0.1.0"
authors = ["sravan <sravans2011@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.1"
juniper = "0.14.1"
